### PR TITLE
add test with markdown-it-attrs

### PR DESCRIPTION
**Pull request by arve0**

### CODE REVIEW

**Comment by windmaomao** [comment]
I wonder if this test actually passed for 

```
    "markdown-it-implicit-figures": "^0.6.0",
    "markdown-it-attrs": "^1.2.1",
```

Because it doesn't work for me. I can try to create a plunker or something tomorrow.

**Comment by arve0** [comment]
Test ran 9 months ago with attrs 0.9.0. I will rerun it, but on mobile now.

**Comment by windmaomao** [comment]
thanks man, appreciate it. Here's a quick question. Is there particular reason why we can't just overwrite the entire html of the image like the following instead of adding more structure to the children token. 

```
function markdownitLinkifyImages (md, config) {
  md.renderer.rules.image = function (tokens, idx, options, env, self) {
    return '' +
      '<a href="' + url + '"' + linkClass + target + '>' +
        '<img src="' + url + '" alt="' + caption + '"' + imgClass + '>' +
      '</a>'
  }
}
```

Other plugin will appreciate it more since they wouldn't know the internal structure of `image`.

**Comment by arve0** [comment]
> Is there particular reason why we can't just overwrite the entire html of the image like the following instead of adding more structure to the children token.

No, there is not a particular reason. It's just one of two possibilities.

Test reran in Travis now with attrs 1.2.1 and did not fail. https://travis-ci.org/arve0/markdown-it-implicit-figures

**Pull request merged**
