### PR TITLE
Support video data type

### PR DESCRIPTION
**Pull request by noomz**

### CODE REVIEW

**Comment by arve0** [comment]
Hi! Thanks for your contribution. I fixed the failing test.

Any thoughts about what file extensions should be considered as movies? What about `.mov`, `.avi`?

Also, should video data-type be configurable, or does one always want `data-type=video` for image links ending in `.mp4`? And, is it even correct to have ``? Or does this render to `<video ...><source src=...` with some plugin?

To get this merged, you should:

1. Answer questions above.
2. Add a test.
3. Document this feature in README.md (example input / output).

**Comment by arve0** [comment]
After reading [this](https://talk.commonmark.org/t/embedded-audio-and-video/441/77), I feel adding `data-type=video` (or rendering to `<video>`) is better handled in the `img`-renderer. 

Or am I missing something? Please add an example input / output of what you want to achieve, so that this PR is more clear.

**Comment by noomz** [comment]
Sorry, its my confusion through the hard-working day. I misunderstood [this plugin](https://github.com/cmrd-senya/markdown-it-html5-embed) is comply against Pandoc document.

I am not sure how should we handle markdown syntax for video tag but it's likely to be like ``, let see another approach [here](https://github.com/brianjgeiger/markdown-it-video) and [here](https://talk.commonmark.org/t/embedded-audio-and-video/441/16).

So in my opinion, as [mozilla docs](https://developer.mozilla.org/en/docs/Web/HTML/Element/figure) 

> Usually a `<figure>` is an image, illustration, diagram, code snippet, etc.

We should add support to `video` tag but it should directly detectable from the `element.tagName` instead of regexp testing.

**Comment by arve0** [comment]
So you want 

```md
![](video.mp4)
```

to render to
```html
<figure>
  <video>
    <source src=video.mp4>
  </video>
</figure>
```

instead of
```html
<p>
  <video>
    <source src=video.mp4>
  </video>
</p>
```
? 

It already does: https://runkit.com/57e36e6e1aeba114000d92f4/591dd8ad67c57f001225d4e5

**Comment by noomz** [comment]
It already does but the `data-type` attribute is not reflect the real element type. Or we should have the way to explicitly assign the data-type.

BTW, your another plugin https://github.com/arve0/markdown-it-attrs is not support implicit figure. (May be I just don't know how to do it)

**Comment by arve0** [comment]
Ahh! I finally get it. Sorry for the confusion, might have been easier if I knew what you wanted as output (didn't know about the video plugins).

So, to get this merged you should:
1. Add a test.
2. Document this feature in README.md with example input / output and usage with your other favorite plugin.

**Comment by arve0** [comment]
> BTW, your another plugin https://github.com/arve0/markdown-it-attrs is not support implicit figure. (May be I just don't know how to do it)

Please open an issue with an example.

**Comment by arve0** [comment]
@noomz attrs plugin should now be supported (markdown-it-attrs version 0.9.0, markdown-it-implicit-figures version 0.6.0).

**Pull request closed without merging**
